### ISSUE TITLE
Support for font awesome  version 5 and up

### ISSUE THREAD

**Issue by the-fapeling** [ghiscoding/Angular-Slickgrid#417]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Angular           | x.y        | 
| Angular-Slickgrid | x.y        | 
| TypeScript        | x.y        | 
| Operating System  | x.y        | 
| NPM/Node/Yarn     | x.y        | 

### Context or Topic 
Hello, so the library does use font awesome for its icons but it only supports till 4.7.2 after that the font awesome changed and where you would list the font awesome dependency as:
"font-awesome": "^4.7.0",

now for later versions its no longer font awesome but : "@fortawesome/fontawesome-free" how Can I set the library to use font awesome version 5 rather than 4.7 ?
### Expected Behavior
For all icons to load and not show the broken icon Icon

### Current Behavior
Icons break , they don't display at all it only shows the rectangle which almost looks the same as the broken image when the image src is not found.

**Comment by ghiscoding** [comment]
Indeed it doesn't support version 5, I wish I could but I don't how to overcome the issue.

What you wrote before about the `$icon-font-family` is that it expects the user to provide a Font Family that is a font **not** an SVG... and that is the problem here, the version 5 is all SVGs. If you take for example the SASS variable [$icon-sort-asc](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/styles/_variables.scss#L123), you can see that it is set to `$icon-sort-asc: "\f0d8" !default;`, that is the associated unicode of that icon character (the `!default` means it can be overriden), this icon can then be used in CSS via the `::before` pseudo in the `content` as shown here
```css
.slick-sort-indicator-asc {
     &:before {
        content: $icon-sort-asc;
     }
}
``` 
So why did I implement it this way? Well that is the way I've found to be able to replace the default icon with any icon I want. But with SVG, I could not find any way to inject an SVG into CSS. Also remember that Angular-Slickgrid is a wrapper of SlickGrid and the only to add (or replace) some icon is to replace them in their original CSS file. 

So again to resume, when it's a real Font, every icon is a character which has an associated unicode version, but there's none for SVG since it's dynamically processed. For example, I'm currently working on a Google Material Design theme and I had to find an associated Font version, which I found [here](https://materialdesignicons.com/), if you can find an associated Font then it would work and you could replace the unicode character. However the downside of a Font is that it's much bigger, since it's a font you'll have to download the entire Font Family (with `.eot`, `.ttf`, `.woff`, `.woff2`) on the other hand SVG are processed on the fly (it's line drawing) so these ones don't have any download per say. 

At the end you have 2 options, either you find how to use an SVG in CSS (I try searching a bit and couldn't find anything) or the second option is to find an associated Font which I believe Font Awesome doesn't provide directly though I could be wrong.

**Comment by ghiscoding** [comment]
I'm going to have to mark this issue as "won't fix" simply because I won't work on it. I've already provided a way to use Font Awesome 5 (by finding and downloading the entire font) and that is the way to go. The main reason of why I use a font is that implementing it this way allows to use many other Font alternative (not just Font Awesome 4) and it also doesn't make sense to go and add multiple CSS classes to support multiple SVG provider. 

What we need is a way to provide the icon through CSS (for a font, we can do it through the `:before` pseudo and add the unicode value to its `content` and be done with it. As far I know, from my research on Google, there's no easy way to do the same with SVG (again that would be how to add an SVG via CSS). 

If anyone else have better way of handling this then please share your info.... for now I'll just close the issue.

**Comment by ghiscoding** [comment]
@the-fapeling 
I'm reopening this issue, I needed SVG as well and after some more research I found how to do it and posted this Stack Overflow [answer](https://stackoverflow.com/a/61660851/1212166). There's some small changes that need to be done in the SASS files, so I'll add that soon. If you read the SO answer I posted, you will notice that you'll need the SVG path and add that to your custom SASS styling file. 

So it will look like this (the SVG below is for Salesforce [icons](https://lightningdesignsystem.com/icons/), so it's different for Font Awesome 5).
```scss
@import './sass-utilities'; // sass helper

/* with SVG */
$icon-sort-color:     #0070d2;
$icon-sort-font-size: 13px;
$icon-sort-asc:       url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" fill="#{encodecolor($icon-sort-color)}" viewBox="0 0 24 24" id="arrowdown"><path d="M19.1 9.7c.4-.4.4-.9 0-1.3l-6.9-6.7c-.4-.4-.9-.4-1.3 0L4 8.4c-.4.4-.4.9 0 1.3l1.3 1.2c.3.4.9.4 1.3 0l2.1-2.1c.4-.4 1-.1 1 .4v12.5c0 .5.5.9 1 .9h1.8c.5 0 .9-.5.9-.9V9.2c0-.5.7-.8 1-.4l2.2 2.1c.4.4.9.4 1.3 0l1.2-1.2z"></path></svg>');
$icon-sort-desc:      url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" fill="#{encodecolor($icon-sort-color)}" viewBox="0 0 24 24" id="arrowdown"><path d="M4.4 14.3c-.3.4-.3.9 0 1.3l7 6.7c.3.4.9.4 1.2 0l7-6.7c.4-.4.4-.9 0-1.3l-1.3-1.2c-.3-.4-.9-.4-1.3 0l-2.1 2.1c-.4.4-1.1.1-1.1-.4V2.3c0-.5-.4-.9-.9-.9h-1.8c-.5 0-.9.5-.9.9v12.5c0 .5-.7.8-1.1.4L7 13.1c-.4-.4-1-.4-1.3 0l-1.3 1.2z"></path></svg>');

@import '../modules/angular-slickgrid/styles/slickgrid-theme-bootstrap.scss';
```

and voilà!!!

Basically you will have to change the SASS variables for all internal icons (sort, checkbox, header menu), there's only a few, less than 10, that requires this while other part of the grid will work with regular css class name (grid menu list, header menu list, ...). We could create a Font Awesome 5 theme as well, I'd be happy to have your help in getting the SVG path for all of the icons defined in the SASS [variable.scss](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/modules/angular-slickgrid/styles/_variables.scss) file (`$icon-sort-asc`, `$icon-sort-desc`, ...).
